name = "Parasitic Horizons"
author = "StynaST, Elibikerdude"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcdd0ecb34baa4876c338cd197ba9b1daf2ac32fb840e14914e7f6c192e0a885"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
