name = "Parasitic Horizons"
author = "StynaST, Elibikerdude"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5be0a82bf1d7051945b78e3241d1c34731a1f0a279d53ca23a7291b74c7124c"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
