// Inscriber
def inscriber = mods.appliedenergistics2.inscriber

inscriber.removeByOutput(item('appliedenergistics2:material:22'))
inscriber.removeByOutput(item('appliedenergistics2:material:23'))
inscriber.removeByOutput(item('appliedenergistics2:material:24'))
crafting.removeByOutput(item('appliedenergistics2:controller'))
crafting.removeByOutput(item('appliedenergistics2:energy_acceptor'))

// Logic
inscriber.recipeBuilder()
    .input(item('srparasites:lurecomponent1'))
    .output(item('appliedenergistics2:material:22'))
    .top(item('appliedenergistics2:material:20'))
    .bottom(item('appliedenergistics2:material:18'))
    .inscribe()
    .register()
// Calculation
inscriber.recipeBuilder()
    .input(item('srparasites:lurecomponent1'))
    .output(item('appliedenergistics2:material:23'))
    .top(item('appliedenergistics2:material:20'))
    .bottom(item('appliedenergistics2:material:16'))
    .inscribe()
    .register()
// Engineering
inscriber.recipeBuilder()
    .input(item('srparasites:lurecomponent1'))
    .output(item('appliedenergistics2:material:24'))
    .top(item('appliedenergistics2:material:20'))
    .bottom(item('appliedenergistics2:material:17'))
    .inscribe()
    .register()

// Crafting Table
crafting.shapedBuilder()
    .output(item('appliedenergistics2:energy_acceptor'))
    .row('ABA')
    .row('BCB')
    .row('ABA')
    .key('A', item('srparasites:semiorganic_ingot'))
    .key('B', item('appliedenergistics2:material:12'))
    .key('C', item('techguns:multiblockmachine:1'))
    .register()

crafting.shapedBuilder()
    .output(item('appliedenergistics2:controller'))
    .row("ABC")
    .row("BDB")
    .row("CBA")
    .key("A", item("srparasites:assimilated_flesh"))
    .key("B", item("appliedenergistics2:material:24"))
    .key("C", item("advancedrocketry:ic:2"))
    .key("D", item("appliedenergistics2:energy_acceptor"))
    .register()